# Upstrem server configuration
upstream_server = "irc.libera.chat"
upstream_port = 6697
usetls = true
ignorecerts = false
password = "" # /PASS password not NickServ or SASL

# Upstream IRC identity
nick = "nicknamehere"

# Core bouncer configuration
verbose = false
dbpath = "test.db"
bind_address = "127.0.0.1:12345"

# This has two uses, it controls the size of the in-memory message cache for messages 
# before they are committed to the database.
# It also controls the number of lines (per buffer) sent to clients on connect.
maxqlen = 5000
